#!/bin/bash
docker login -pcqyidaoyun123 --username=江苏一道云科技发展有限公司 registry.cn-hangzhou.aliyuncs.com
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-train_allinone-openstackc:v1.0-b3
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-train_allinone-openstackc:v1.0-b2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-train_allinone-openstackc:v1.0-b1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.2-kubevirtc-lvm:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-openstackc-python22:v2.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-kubevirtc-python22-31:v2.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-openstackc-python32:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-kubevirtc-python16.32:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-centos7.5-kubevirtc-openstack-train-allinone:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.2-kubevirtc-iaas_mitaka_allinone:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.5-kubevirtc-python37:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl4.8:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl4.7:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl6.10:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl5.9:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl1-5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-yjswl4.6:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-kubevirtc-1xprimary3.8:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-javaweb:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-xnhjs2.1:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-xnhjs4.5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs6.13:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs3.5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs8.20:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-centos7.5-openstackc-wpmtc3_single:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-centos7.5-openstackc-gpmallmtc3_single:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs6.14:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs7.18:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-xnhjs5.7:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.2-kubevirtc-paas_allinone:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.5-kubevirtc-1xprimary5.10:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.2-kubevirtc-centos7.2:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-s-centos7.2-kubevirtc-rqjs1.1:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-g-centos7.5-kubevirtc-centos7.5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ydy-m-centos7.5-dockerc:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base-cn:v4
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-7.4:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-7.3:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-4.4:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-3.12:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base:v4
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-7.3:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-5.5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-5.4:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-4.5:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-3.10:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-3.8:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-primary-3.6:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-5.8:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-3.9:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base:v3
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base-cn:v3
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos7.5-sshd:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos:7.5.1804
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-4.12:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/1x-intermediate-4.3:v1.0
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base-cn:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/theia-java:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/theia-ide:light_latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/python:3.5-alpine
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/nginx:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/hadoop-bigdata-task_2.1:v3
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ubuntu-desktop-experiment-base-en:stable
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/java_web_dev_tools:v5
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/web_crawler:v1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_21:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_18-20:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_15-17:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_12-14:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_4-11:v2
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-desktop-base:v1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/ubuntu-desktop-ssh-mysql:v1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos-bigdata-ex_1-3:v1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/movie-tag-images-experiment_2-6:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/movie-tag-images-experiment_1:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/mysql-course-2:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/mysql-course-1:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/dmlabone:v1
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/centos7.2_xiandian:latest
docker pull registry.cn-hangzhou.aliyuncs.com/zhixuetong-images/python:3.4-alpine