apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vpa
  template:
    metadata:
      labels:
        app: nginx-vpa
    spec:
      containers:
      - name: nginx-vpa
        image: swr.cn-north-1.myhuaweicloud.com/kongyu/nginx:1.7.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 10Mi
          requests:
            cpu: 50m
            memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vpa
  namespace: default
  labels:
    app: nginx-vpa
spec:
  type: NodePort
  selector:
    app: nginx-vpa
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32500

