---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-centos7.5
  name: vm-centos7.5
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-centos7.5
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
#          limits:
#            cpu: 1000m
#            memory: 1Gi
# 加了限制启动会很慢
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            bridge: {}
          - name: macvlan
            bridge: {}
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      - name: net
        multus:
          networkName: macvlan
        name: macvlan
      volumes:
      - name: containerdisk
        containerDisk:
          image: swr.cn-north-1.myhuaweicloud.com/kongyu/kubevirt/centos:centos7.9.2009
      - name: emptydisk
        emptyDisk:
          capacity: 10Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #!/bin/sh
            echo 000000 | passwd --stdin root 
            dhclient eth1
