kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: longhorn-pvc
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: longhorn-test-pod
spec:
  containers:
  - name: longhorn-test-pod
    image: busybox
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "touch /mnt/SUCCESS && ls /mnt"
    volumeMounts:
    - name: pvc
      mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: longhorn-pvc
