---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-template
  namespace: test
  labels:
    app: app-template
spec:
  persistentVolumeReclaimPolicy: Delete  # Delete Retain
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.yidaoyun.local
    path: /data/nfs/temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-template
  namespace: test
  labels:
    app: app-template
spec:
  storageClassName: ""
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: app-template
