---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: test
  labels:
    app: storage
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: test
spec:
  selector:
    app: storage
  type: NodePort
  ports:
  - name: storage
    port: 23000
    targetPort: 23000
    nodePort: 33000
  - name: nginx
    port: 8888
    targetPort: 8888
    nodePort: 18888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      terminationGracePeriodSeconds: 0
      hostname: storage
      containers:
      - name: storage
        image: registry.cn-hangzhou.aliyuncs.com/zhixuetong-base/fastdfs:1.0
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1024Mi
#          requests:
#            cpu: 1000m
#            memory: 1024Mi
        ports:
        - name: storage
          containerPort: 23000
        - name: nginx
          containerPort: 8888
        env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TRACKER_SERVER
            value: tracker.$(HOST):22122
          - name: GROUP_NAME
            value: group1
        command: ["/usr/bin/start1.sh","storage"]
        livenessProbe:
          tcpSocket:
            port: 23000
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 23000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/fdfs
        - name: localtime
          readOnly: true
          mountPath: /etc/localtime
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: storage
      - name: localtime
        hostPath:
          type: File
          path: /etc/localtime
