---
apiVersion: v1
kind: PersistentVolumeClaim  ## 存储卷供用户创建的工作负载使用，是将工作负载数据持久化的一种资源对象。
metadata:
  namespace: test  ## 命名空间
  name: minio  ## 名称
  labels:  ## 标签
    app: minio
  annotations:
    ## 描述信息
    kubesphere.io/description: minio template
spec:
#  storageClassName: local  ## 存储类型(StorageClass)是由集群管理员配置存储服务端参数，并按类型提供存储给集群用户使用。
  accessModes:  ## 访问模式
    - ReadWriteOnce
    ## ReadWriteOnce：可读科写，但支持被单个node挂载
    ## ReadOnlyMany：可以以读的方式被多个node挂载
    ## ReadWriteMany：可以以读写的方式被多个node挂载
  resources:
    requests:
      storage: 10Gi  ## 存储卷容量
---
apiVersion: v1
kind: Service  ## 服务 (Service) 是定义了一类容器组的逻辑集合和一个用于访问它们的策略。
metadata:
  namespace: test  ## 命名空间
  name: minio  ## 名称
  labels:  ## 服务标签
    app: minio
  annotations:
    ## 描述信息
    kubesphere.io/description: minio template
spec:
  selector:  ## 指定工作负载
    app: minio  ## 工作负载标签
  ports:  ## 设置容器镜像暴露的端口以及服务端口
    - name: minio  ## 名称
      protocol: TCP  ## 协议
      targetPort: 9000  ## 服务端口
      port: 9000  ## 容器端口
      nodePort: 9001  ## 节点端口
    - name: minio-console  ## 名称
      protocol: TCP  ## 协议
      targetPort: 9001  ## 服务端口
      port: 9001  ## 容器端口
      nodePort: 9002  ## 节点端口
  type: NodePort  ## 通过访问集群节点的对应端口来访问服务(NodePort)
  sessionAffinityConfig:  ## 开启回话保持
    clientIP:
      timeoutSeconds: 10800  ## 最大会话保持时间(秒)，会话保持时间默认是 10800 秒(即 3 小时)

---
apiVersion: apps/v1
kind: Deployment  ## 工作负载 (Workload) 通常是访问服务的实际载体, 也是对节点日志收集、监控等系统应用的实际运行载体，是对一组容器组 (Pod) 的抽象模型
metadata:
  namespace: test  ## 命名空间
  name: minio  ## 名称
  labels:  ## 应用标签
    app: minio
  annotations:
    ## 描述信息
    kubesphere.io/description: minio template
spec:
  replicas: 1  ## 容器组副本数量
  selector:
    matchLabels:  ## 应用标签
      app: minio
  template:
    metadata:
      labels:  ## 应用标签
        app: minio
    spec:
#      nodeSelector:  ## 匹配节点
#        app: minio  ## 匹配节点标签
      terminationGracePeriodSeconds: 0  ## 优雅地终止容器，默认30秒。
      restartPolicy: Always  ## 容器重启策略，Always、OnFailure和Never。默认值是Always。
      hostname: minio  ## 容器主机名
      containers:
        - name: minio
          imagePullPolicy: IfNotPresent
          ## IfNotPresent：优先使用本地镜像，如果本地存在镜像就优先使用本地镜像
          ## Always：尝试重新下载镜像，在创建及更新时，每次都会尝试下载新的镜像
          ## Never：仅使用本地镜像，仅会使用本地镜像，如果本地不存在所需镜像，则会导致容器异常
          image: swr.cn-north-1.myhuaweicloud.com/kongyu/minio:vlatest  ## 镜像
          ports:  ## 端口设置
            - name: minio  ## 名称
              protocol: TCP  ## 协议
              containerPort: 9000  ## 容器端口
            - name: minio-console  ## 名称
              protocol: TCP  ## 协议
              containerPort: 9001  ## 容器端口
#          resources:  ## 设置容器的资源限制与资源预留，这将能够帮助系统更好地调度容器，提高稳定性。
#            requests:  ## 资源预留
#              cpu: '0.5'
#              memory: 512Mi
#            limits:  ## 资源限制
#              cpu: '1'
#              memory: 1024Mi
          livenessProbe:  ## 容器存活检查
            tcpSocket:  ## TCP端口检查
              port: 9000  ## TCP端口
            initialDelaySeconds: 120  ## 初始延迟(秒)：在检查其运行状况之前，容器启动后需要等待多长时间。
            timeoutSeconds: 5  ## 超时时间(秒)：等待探针完成多长时间。如果超过时间，则认为探测失败。默认为1秒。最小值为1。
            periodSeconds: 30  ## 执行探测频率(秒)：执行探测的频率（以秒为单位）。默认为10秒。最小值为1。
            successThreshold: 1  ## 健康阈值：探测失败后，连续最小成功探测为成功。默认值为1。最小值为1。存活探针和启动探针内必须为1。
            failureThreshold: 10  ## 不健康阈值：探针进入失败状态时需要连续探测失败的最小次数。
          readinessProbe:  ## 就绪探针
            tcpSocket:  ## TCP端口探针
              port: 9000  ## TCP端口
            initialDelaySeconds: 5  ## 初始延迟(秒)：在检查其运行状况之前，容器启动后需要等待多长时间。
            timeoutSeconds: 5  ## 超时时间(秒)：等待探针完成多长时间。如果超过时间，则认为探测失败。默认为1秒。最小值为1。
            periodSeconds: 30  ## 执行探测频率(秒)：执行探测的频率（以秒为单位）。默认为10秒。最小值为1。
            successThreshold: 1  ## 健康阈值：探测失败后，连续最小成功探测为成功。默认值为1。最小值为1。存活探针和启动探针内必须为1。
            failureThreshold: 3  ## 不健康阈值：探针进入失败状态时需要连续探测失败的最小次数。
          command:
            - "/bin/sh"
            - "-ce"
            - "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server --address :9000 --console-address :9001  /data"
          env:  ## 容器环境变量
            - name: MINIO_ROOT_USER
              value: "admin"
            - name: MINIO_ROOT_PASSWORD
              value: "admin123"
          volumeMounts:  ## 存储卷挂载
            - name: data  ## 匹配存储卷
              mountPath: /data  ## 存储卷挂载路径
            - name: localtime  ## 匹配存储卷
              mountPath: /etc/localtime  ## 存储卷挂载路径
              readOnly: true  ## 只读挂载
      volumes:  ## 存储卷
        - name: data  ## 存储卷名称
          persistentVolumeClaim:  ## 匹配同一命名空间的PVC
            claimName: minio  ## 匹配PVC名称
            readOnly: false  ## VolumeMounts的只读设置，默认的false。
        - name: localtime  ## 同步主机时间
          hostPath:  ## 从宿主机挂载
            type: File  ## 文件类型
            path: /etc/localtime  ## 宿主机路径

