---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novnc
  namespace: test
  labels:
    app: novnc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: novnc
  namespace: test
spec:
  selector:
    app: novnc
  type: NodePort
  ports:
  - name: novnc
    port: 6080
    targetPort: 6080
    nodePort: 16080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      terminationGracePeriodSeconds: 0
      hostname: novnc
      containers:
      - name: novnc
        image: registry.cn-hangzhou.aliyuncs.com/zhixuetong-base/novnc:1.0
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1024Mi
#          requests:
#            cpu: 1000m
#            memory: 1024Mi
        ports:
        - containerPort: 6080
          name: novnc
        livenessProbe:
          tcpSocket:
            port: 6080
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /usr/local/noVNC/tokens/
        - name: localtime
          readOnly: true
          mountPath: /etc/localtime
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: novnc
      - name: localtime
        hostPath:
          type: File
          path: /etc/localtime

