---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker
  namespace: test
  labels:
    app: tracker
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tracker
  namespace: test
spec:
  selector:
    app: tracker
  type: NodePort
  ports:
  - name: tracker
    port: 22122
    targetPort: 22122
    nodePort: 32122
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      terminationGracePeriodSeconds: 0
      hostname: tracker
      containers:
      - name: tracker
        image: registry.cn-hangzhou.aliyuncs.com/zhixuetong-base/fastdfs:1.0
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 1000m
#            memory: 1024Mi
#          requests:
#            cpu: 1000m
#            memory: 1024Mi
        ports:
        - containerPort: 22122
          name: tracker
        command: ["/usr/bin/start1.sh","tracker"]
        livenessProbe:
          tcpSocket:
            port: 22122
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 22122
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/fdfs
        - name: localtime
          readOnly: true
          mountPath: /etc/localtime
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tracker
      - name: localtime
        hostPath:
          type: File
          path: /etc/localtime
